module.exports = {
  COUNTRY: "Country",
  PRODUCT: "Product",
  PRICE: "Price",
  COUPON: "Coupon",
  USER: "User",
  CONTACT: "Contact",
  PREFERENCE: "Preference",
  VEHICLE: "Vehicle",
  ADDRESS: "Address",
  SUBSCRIPTION: "Subscription",
  TRIP: "Trip",
  INVOICE: "Invoice",
  PARTICIPANT: "Participant",
  CONVEYANCE: "Conveyance",
  LOCATION: "Location",
  WAYPOINT: "Waypoint",
  JOURNEY: "Journey",
  TENANCY: "Tenancy",
  ACTION_ITEM: "ActionItem",
  EXPENSE: "Expense",
  ATTACHMENT: "Attachment",
  FOOTPRINT: "Footprint",
};
